INSERT INTO veterinary_clinic_animal (name, group_id, owner_id)
VALUES
	('Albi', 1, 1),
	('Bady', 1, 2),
	('Princ', 1, 3),
	('Scooby doo', 1, 4),
	('Jimmy', 1, 1),
	('Kulička', 2, 3),
	('Lajdák', 2, 2),
	('Macek', 2, 3),
	('Sněhulka', 2, 4),
	('Ťapka', 2, 4),
	('Amadeus', 3, 5),
	('Azurit', 3, 5),
	('Bart', 3, 5),
	('Bambuča', 3, 6),
	('Inhalátor', 3, 6),
	('Houmr', 4, 6),
	('Hubert', 4, 6),
	('Hlad', 4, 1),
	('Henry', 4, 2),
	('Ralf', 4, 3),
	('Roko', 5, 1),
	('Samson', 5, 1),
	('Ušisko', 5, 2),
	('Rebel', 5, 3),
	('Jupiter', 5, 4),
	('Sandokan', 1, 3),
	('Abbie', 1, 2),
	('Bety', 1, 3),
	('Čoklit', 1, 6),
	('Chlupáč', 2, 5),
	('Aragorn', 2, 4),
	('Justin', 2, 3);