# Generated by Django 3.1.6 on 2021-02-04 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='jméno')),
            ],
        ),
        migrations.CreateModel(
            name='AnimalGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='jméno')),
            ],
        ),
        migrations.CreateModel(
            name='AnimalOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='jméno')),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Jméno')),
                ('in_stock', models.IntegerField(verbose_name='skladem')),
            ],
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField(verbose_name='diagnóza')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='cena')),
                ('date', models.DateTimeField(verbose_name='datum vyšetření')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinary_clinic.animal', verbose_name='zvíře')),
                ('medicaments', models.ManyToManyField(to='veterinary_clinic.Medicament')),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='veterinary_clinic.animalgroup', verbose_name='skupina'),
        ),
        migrations.AddField(
            model_name='animal',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='veterinary_clinic.animalowner', verbose_name='majitel'),
        ),
    ]
