# Generated by Django 3.1.6 on 2021-02-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary_clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='medicaments',
            field=models.ManyToManyField(blank=True, null=True, to='veterinary_clinic.Medicament'),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='name',
            field=models.CharField(max_length=60, verbose_name='jméno'),
        ),
    ]
