# Generated by Django 3.1.6 on 2021-02-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary_clinic', '0003_auto_20210206_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='medicaments',
            field=models.ManyToManyField(blank=True, to='veterinary_clinic.Medicament'),
        ),
    ]
