# Generated by Django 3.1.6 on 2021-02-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary_clinic', '0004_auto_20210206_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalowner',
            name='surname',
            field=models.CharField(default='default', max_length=60, verbose_name='příjmení'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='name',
            field=models.CharField(max_length=60, verbose_name='název'),
        ),
    ]
