# Generated by Django 3.1.6 on 2021-02-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary_clinic', '0005_auto_20210206_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='medicaments',
            field=models.ManyToManyField(blank=True, to='veterinary_clinic.Medicament', verbose_name='podané léky'),
        ),
    ]
