# Generated by Django 3.1.6 on 2021-02-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary_clinic', '0007_remove_medicament_in_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='date',
            field=models.DateField(verbose_name='datum vyšetření'),
        ),
    ]
